sudo: required

services:
  - docker

script: docker-compose run compile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci dashboard
  local_dir: ./docs/
  on:
    branch: master
